import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { Button, Chip, Divider, Icon, IconButton, Surface, Text } from 'react-native-paper';
import { useLocalSearchParams, useRouter, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { useSQLiteContext } from '../../src/data/database';
import { deleteTask, getTask, toggleSubtask, updateTaskStatus } from '../../src/data/taskRepository';
import { colors } from '../../src/theme/colors';
import { cancelTaskNotifications } from '../../src/data/notificationRepository';

export default function TaskDetail(){
 const router=useRouter(), db=useSQLiteContext(), {id}=useLocalSearchParams(), [task,setTask]=useState(null);
 const load=useCallback(async()=>setTask(await getTask(db,id)),[db,id]); useFocusEffect(useCallback(()=>{load()},[load]));
 if(!task)return <View style={styles.loading}><Text>Cargando tarea...</Text></View>;
 const complete=async()=>{await updateTaskStatus(db,id,'Completada');load()};
 const changeStatus=async(status)=>{await updateTaskStatus(db,id,status);load()};
 const remove=()=>Alert.alert('Eliminar tarea','¿Deseas eliminar esta tarea?', [{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{await cancelTaskNotifications(db,id);await deleteTask(db,id);router.back()}}]);
 return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><IconButton icon="arrow-left" onPress={()=>router.back()}/><Text variant="titleLarge" style={styles.title}>Detalle de tarea</Text><IconButton icon="pencil-outline" onPress={()=>router.push(`/task/edit?id=${id}`)}/><IconButton icon="delete-outline" onPress={remove}/></View>
 <Surface style={styles.card} elevation={0}><View style={styles.taskTitle}><View style={[styles.dot,{backgroundColor:task.category_color||colors.primary}]}/><Text variant="titleLarge" style={styles.name}>{task.title}</Text></View><View style={styles.statuses}>{['Pendiente','En progreso','Completada','Cancelada'].map(s=><Chip key={s} selected={task.status===s} onPress={()=>changeStatus(s)} style={styles.statusChip}>{s}</Chip>)}</View><Divider style={styles.divider}/><Text variant="bodyLarge" style={styles.description}>{task.description||'Sin descripción.'}</Text><Info icon="calendar-outline" text={task.due_date}/><Info icon="clock-outline" text={task.due_time||'Sin hora'}/><Info icon="folder-outline" text={task.category||'Sin categoría'}/><Info icon="flag-outline" text={`Prioridad ${task.priority.toLowerCase()}`}/><Info icon="bell-outline" text={task.reminder_enabled?`${task.reminder_minutes===0?'A la hora de la tarea':task.reminder_minutes>=60?`${task.reminder_minutes/60} hora${task.reminder_minutes===60?'':'s'} antes`: `${task.reminder_minutes} minutos antes`}`:'Sin recordatorio'}/><Info icon="repeat" text={task.recurrence}/>{task.notes?<Info icon="note-text-outline" text={task.notes}/>:null}</Surface>
 <Surface style={styles.card} elevation={0}><View style={styles.subHeader}><Text variant="titleMedium" style={styles.sectionTitle}>Subtareas ({task.subtasks.filter(s=>s.completed).length}/{task.subtasks.length})</Text></View>{task.subtasks.length?task.subtasks.map(s=><View key={s.id} style={styles.subtask}><Icon source={s.completed?'checkbox-marked':'checkbox-blank-outline'} color={s.completed?colors.primary:colors.muted} size={21}/><Text onPress={async()=>{await toggleSubtask(db,s.id,!s.completed);load()}} style={[{flex:1},s.completed?styles.done:null]}>{s.title}</Text></View>):<Text style={styles.muted}>No hay subtareas todavía.</Text>}</Surface>
 <Button mode="contained" icon="check" disabled={task.status==='Completada'} onPress={complete} style={styles.button}>{task.status==='Completada'?'Completada':'Marcar como completada'}</Button></ScrollView>;
}
function Info({icon,text}){return <View style={styles.info}><Icon source={icon} size={19} color={colors.muted}/><Text style={styles.infoText}>{text}</Text></View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingTop:45,paddingBottom:50},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',marginHorizontal:-8,marginBottom:16},title:{flex:1,fontWeight:'800'},card:{backgroundColor:'#FFF',borderRadius:20,padding:18,marginBottom:14},taskTitle:{flexDirection:'row',alignItems:'center',gap:10},dot:{width:12,height:12,borderRadius:6},name:{flex:1,fontWeight:'800'},statuses:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:14},statusChip:{backgroundColor:'#F2F1FF'},divider:{marginVertical:16},description:{lineHeight:22,marginBottom:14},info:{flexDirection:'row',alignItems:'center',gap:10,marginVertical:6},infoText:{color:colors.text,flex:1},subHeader:{flexDirection:'row',justifyContent:'space-between',marginBottom:12},sectionTitle:{fontWeight:'800'},subtask:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:8},done:{color:colors.muted,textDecorationLine:'line-through'},muted:{color:colors.muted},button:{marginTop:4,borderRadius:14}});
