import { ScrollView, StyleSheet, View, Pressable } from 'react-native';
import { FAB, IconButton, Surface, Text } from 'react-native-paper';
import { useRouter, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { useSQLiteContext } from '../../src/data/database';
import { getTasks, toTaskCard, updateTaskStatus } from '../../src/data/taskRepository';
import { useAppTheme } from '../../src/theme/ThemeContext';
import { cancelTaskNotifications } from '../../src/data/notificationRepository';
import { weekFrom, toLocalDateKey, formatDateEs } from '../../src/data/date';
import TaskCard from '../../src/components/TaskCard';
export default function Calendar(){const router=useRouter(),db=useSQLiteContext(),{palette}=useAppTheme();const days=useMemo(()=>weekFrom(),[]),[selected,setSelected]=useState(toLocalDateKey()),[tasks,setTasks]=useState([]);const load=useCallback(async()=>setTasks((await getTasks(db,{date:selected})).map(toTaskCard)),[db,selected]);useFocusEffect(useCallback(()=>{load()},[load]));const toggle=async t=>{const nextStatus=t.status==='Completada'?'Pendiente':'Completada'; await updateTaskStatus(db,t.id,nextStatus); if(nextStatus==='Completada') await cancelTaskNotifications(db,t.id); load()};return <View style={[styles.container,{backgroundColor:palette.background}]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text variant="labelLarge" style={{color:palette.primary,fontWeight:'800'}}>PLANIFICA</Text><Text variant="headlineSmall" style={[styles.title,{color:palette.text}]}>Calendario</Text></View><IconButton icon="calendar-today" mode="contained-tonal"/></View><Surface style={[styles.calendar,{backgroundColor:palette.surface,borderColor:palette.border}]} elevation={0}><View style={styles.week}>{days.map(d=>{const active=selected===d.key;return <Pressable key={d.key} onPress={()=>setSelected(d.key)} style={[styles.day,{borderColor:active?palette.primary:'transparent',backgroundColor:active?palette.primary:'transparent'}]}><Text style={{color:active?'#FFF':palette.muted,fontSize:11,fontWeight:'700'}}>{d.day}</Text><Text style={{color:active?'#FFF':palette.text,fontWeight:'850',marginTop:5}}>{d.date}</Text><View style={[styles.dot,{backgroundColor:active?'#FFF':palette.primary}]}/></Pressable>})}</View></Surface><View style={styles.dayTitle}><View><Text variant="titleLarge" style={{color:palette.text,fontWeight:'850'}}>{formatDateEs(selected)}</Text><Text style={{color:palette.muted}}>{tasks.length} tareas programadas</Text></View>{selected===toLocalDateKey()?<Text style={{color:palette.primary,fontWeight:'800'}}>Hoy</Text>:null}</View>{tasks.length?tasks.map((task,i)=><TaskCard key={task.id} task={task} index={i} onToggle={()=>toggle(task)} onPress={()=>router.push(`/task/${task.id}`)}/>):<Text style={{color:palette.muted,paddingVertical:40,textAlign:'center'}}>No hay tareas para este día.</Text>}</ScrollView><FAB icon="plus" label="Nueva tarea" style={[styles.fab,{backgroundColor:palette.primary}]} color="#FFF" onPress={()=>router.push('/task/new')}/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:20,paddingTop:55,paddingBottom:125},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},title:{fontWeight:'850',marginTop:3},calendar:{borderRadius:20,padding:10,borderWidth:1},week:{flexDirection:'row',justifyContent:'space-between'},day:{width:43,height:64,borderRadius:15,alignItems:'center',justifyContent:'center',borderWidth:1.5},dot:{width:4,height:4,borderRadius:2,marginTop:6},dayTitle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:22,marginBottom:12},fab:{position:'absolute',right:18,bottom:88,borderRadius:18}});
