import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { FAB, Icon, IconButton, Surface, Text, TextInput, Button } from 'react-native-paper';
import { useSQLiteContext } from '../../src/data/database';
import { createCategory, deleteCategory, getCategories, updateCategory } from '../../src/data/taskRepository';
import { useAppTheme } from '../../src/theme/ThemeContext';
import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
export default function Categories(){const db=useSQLiteContext(),{palette}=useAppTheme(),[cats,setCats]=useState([]),[show,setShow]=useState(false),[name,setName]=useState(''),[editing,setEditing]=useState(null);const load=useCallback(()=>getCategories(db).then(setCats),[db]);useFocusEffect(useCallback(()=>{load()},[load]));const save=async()=>{if(!name.trim())return;if(editing)await updateCategory(db,editing.id,{name,icon:editing.icon,color:editing.color});else await createCategory(db,{name});setName('');setEditing(null);setShow(false);load()};const remove=c=>Alert.alert('Eliminar categoría',`¿Eliminar "${c.name}"? Las tareas quedarán sin categoría.`,[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{await deleteCategory(db,c.id);load()}}]);return <View style={[styles.container,{backgroundColor:palette.background}]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text variant="labelLarge" style={{color:palette.primary,fontWeight:'800'}}>ORGANIZA</Text><Text variant="headlineSmall" style={[styles.title,{color:palette.text}]}>Categorías</Text></View><IconButton icon="plus" mode="contained-tonal" onPress={()=>{setEditing(null);setName('');setShow(true)}}/></View>{cats.map(c=><Surface key={c.id} style={[styles.card,{backgroundColor:palette.surface,borderColor:palette.border}]} elevation={0}><View style={[styles.icon,{backgroundColor:`${c.color}20`}]}><Icon source={c.icon} color={c.color} size={22}/></View><View style={styles.info}><Text variant="titleMedium" style={[styles.name,{color:palette.text}]}>{c.name}</Text><Text style={{color:palette.muted}}>{c.task_count} tareas</Text></View><IconButton icon="pencil-outline" size={19} onPress={()=>{setEditing(c);setName(c.name);setShow(true)}}/><IconButton icon="delete-outline" size={19} onPress={()=>remove(c)}/></Surface>)}{show&&<Surface style={[styles.editor,{backgroundColor:palette.surface,borderColor:palette.border}]} elevation={2}><Text variant="titleMedium" style={[styles.editorTitle,{color:palette.text}]}>{editing?'Editar categoría':'Nueva categoría'}</Text><TextInput label="Nombre" value={name} onChangeText={setName} mode="outlined" style={[styles.input,{backgroundColor:palette.surface}]}/><View style={styles.editorRow}><Button onPress={()=>{setShow(false);setEditing(null)}}>Cancelar</Button><Button mode="contained" onPress={save}>Guardar</Button></View></Surface>}</ScrollView><FAB icon="plus" style={[styles.fab,{backgroundColor:palette.primary}]} color="#FFF" onPress={()=>{setEditing(null);setName('');setShow(true)}}/></View>}
const styles=StyleSheet.create({container:{flex:1},content:{padding:20,paddingTop:55,paddingBottom:110},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},title:{fontWeight:'800'},card:{flexDirection:'row',alignItems:'center',padding:8,borderRadius:16,borderWidth:1,marginBottom:10},icon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},info:{flex:1,marginLeft:10},name:{fontWeight:'700'},editor:{padding:16,borderRadius:18,borderWidth:1,marginTop:8},editorTitle:{fontWeight:'800',marginBottom:12},editorRow:{flexDirection:'row',justifyContent:'flex-end',gap:8},input:{marginBottom:12},fab:{position:'absolute',right:20,bottom:88,borderRadius:18}});
