import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { FAB, Icon, IconButton, Surface, Text, TextInput, Button } from 'react-native-paper';
import { useSQLiteContext } from '../../src/data/database';
import { createCategory, deleteCategory, getCategories, updateCategory } from '../../src/data/taskRepository';
import { colors } from '../../src/theme/colors';
import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';

export default function Categories(){
 const db=useSQLiteContext(),[cats,setCats]=useState([]),[show,setShow]=useState(false),[name,setName]=useState(''),[editing,setEditing]=useState(null);
 const load=useCallback(()=>getCategories(db).then(setCats),[db]); useFocusEffect(useCallback(()=>{load()},[load]));
 const save=async()=>{if(!name.trim())return;if(editing)await updateCategory(db,editing.id,{name,icon:editing.icon,color:editing.color});else await createCategory(db,{name});setName('');setEditing(null);setShow(false);load()};
 const remove=(c)=>Alert.alert('Eliminar categoría',`¿Eliminar "${c.name}"? Las tareas quedarán sin categoría.`,[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{await deleteCategory(db,c.id);load()}}]);
 return <View style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text variant="headlineSmall" style={styles.title}>Categorías</Text><IconButton icon="plus" iconColor={colors.primary} onPress={()=>{setEditing(null);setName('');setShow(true)}}/></View>{cats.map(c=><Surface key={c.id} style={styles.card} elevation={0}><View style={[styles.icon,{backgroundColor:`${c.color}20`}]}><Icon source={c.icon} color={c.color} size={22}/></View><View style={styles.info}><Text variant="titleMedium" style={styles.name}>{c.name}</Text><Text style={styles.count}>{c.task_count} tareas</Text></View><IconButton icon="pencil-outline" size={19} onPress={()=>{setEditing(c);setName(c.name);setShow(true)}}/><IconButton icon="delete-outline" size={19} onPress={()=>remove(c)}/></Surface>)}{show&&<Surface style={styles.editor} elevation={2}><Text variant="titleMedium" style={styles.editorTitle}>{editing?'Editar categoría':'Nueva categoría'}</Text><TextInput label="Nombre" value={name} onChangeText={setName} mode="outlined" style={{backgroundColor:'#FFF',marginBottom:12}}/><View style={styles.editorRow}><Button onPress={()=>{setShow(false);setEditing(null)}}>Cancelar</Button><Button mode="contained" onPress={save}>Guardar</Button></View></Surface>}</ScrollView><FAB icon="plus" style={styles.fab} onPress={()=>{setEditing(null);setName('');setShow(true)}}/></View>
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingTop:55,paddingBottom:110},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},title:{fontWeight:'800'},card:{flexDirection:'row',alignItems:'center',padding:8,borderRadius:16,backgroundColor:'#FFF',marginBottom:10},icon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},info:{flex:1,marginLeft:10},name:{fontWeight:'700'},count:{color:colors.muted,marginTop:2},editor:{padding:16,borderRadius:18,backgroundColor:'#FFF',marginTop:8},editorTitle:{fontWeight:'800',marginBottom:12},editorRow:{flexDirection:'row',justifyContent:'flex-end',gap:8},fab:{position:'absolute',right:20,bottom:88,backgroundColor:colors.primary}});
