import { ScrollView, StyleSheet, View } from 'react-native';
import { Surface, Text } from 'react-native-paper';
import { useSQLiteContext } from '../../src/data/database';
import { getStats } from '../../src/data/taskRepository';
import { useCallback, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { colors } from '../../src/theme/colors';

export default function Stats(){const db=useSQLiteContext();const[stats,setStats]=useState({totals:{total:0,completed:0,pending:0,in_progress:0},priorities:[]});const load=useCallback(async()=>setStats(await getStats(db)),[db]);useFocusEffect(useCallback(()=>{load()},[load]));const total=Number(stats.totals?.total||0);return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Text variant="headlineSmall" style={styles.title}>Estadísticas</Text><View style={styles.metrics}><Stat value={total} label="Total de tareas"/><Stat value={Number(stats.totals?.completed||0)} label="Completadas"/><Stat value={total?`${Math.round(Number(stats.totals?.completed||0)/total*100)}%`:'0%'} label="Progreso"/></View><Surface style={styles.panel} elevation={0}><Text variant="titleMedium" style={styles.panelTitle}>Tareas por estado</Text><Row name="Pendientes" count={Number(stats.totals?.pending||0)} max={total} color={colors.urgent}/><Row name="En progreso" count={Number(stats.totals?.in_progress||0)} max={total} color={colors.blue}/><Row name="Completadas" count={Number(stats.totals?.completed||0)} max={total} color={colors.green}/></Surface><Surface style={styles.panel} elevation={0}><Text variant="titleMedium" style={styles.panelTitle}>Tareas por prioridad</Text>{['Urgente','Alta','Media','Baja'].map((name,i)=>{const count=Number(stats.priorities.find(p=>p.priority===name)?.count||0);return <Row key={name} name={name} count={count} max={Math.max(total,1)} color={[colors.urgent,colors.high,colors.medium,colors.low][i]}/>})}</Surface></ScrollView>}
function Row({name,count,max,color}){return <View style={styles.row}><Text style={styles.rowName}>{name}</Text><View style={styles.track}><View style={[styles.fill,{width:`${Math.min(100,max?count/max*100:0)}%`,backgroundColor:color}]}/></View><Text>{count}</Text></View>}
function Stat({value,label}){return <Surface style={styles.stat} elevation={0}><Text variant="headlineSmall" style={styles.value}>{value}</Text><Text variant="labelSmall" style={styles.label}>{label}</Text></Surface>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingTop:55,paddingBottom:40},title:{fontWeight:'800',marginBottom:18},metrics:{flexDirection:'row',gap:9},stat:{flex:1,padding:14,borderRadius:16,backgroundColor:'#FFF',alignItems:'center'},value:{fontWeight:'800',color:colors.primary},label:{color:colors.muted,textAlign:'center',marginTop:4},panel:{marginTop:14,borderRadius:18,padding:16,backgroundColor:'#FFF'},panelTitle:{fontWeight:'800',marginBottom:16},row:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:13},rowName:{width:78},track:{flex:1,height:8,borderRadius:4,backgroundColor:'#EEF0F5',overflow:'hidden'},fill:{height:'100%',borderRadius:4}});
